name: 🧪 Typecheck

run-name: Typecheck ${{github.sha}}

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ">=22"
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Install typescript
        run: npm i -g typescript

      - name: Typecheck
        run: tsc
