name: Deploy Github Pages

run-name: Deploy ${{ github.sha }} to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        id: checkout
        uses: actions/checkout@v4

      - name: Install packages
        id: install
        run: npm install --legacy-peer-deps

      - name: LS
        id: ls
        run: ls && pwd && ls /home/runner/work/divesea && ls /home/runner/work/divesea/divesea && ls /home/runner/work/divesea/divesea/src/shared/ui/Nav

      - name: Build static files
        id: build
        run: npm run build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
